services:
    sonata.admin.compta.type:
        class: ProjetNormandie\ComptaBundle\Admin\TypeAdmin
        tags:
            - { name: sonata.admin, model_class: 'ProjetNormandie\ComptaBundle\Entity\Type', manager_type: orm, group: "group.compta", label: "label.type" }
        arguments: [ ~, ~, ~ ]
    sonata.admin.compta.source:
        class: ProjetNormandie\ComptaBundle\Admin\SourceAdmin
        tags:
            - { name: sonata.admin, model_class: 'ProjetNormandie\ComptaBundle\Entity\Source', manager_type: orm, group: "group.compta", label: "label.source" }
        arguments: [ ~, ~, ~ ]
    sonata.admin.compta.donation:
        class: ProjetNormandie\ComptaBundle\Admin\DonationAdmin
        tags:
            - { name: sonata.admin, model_class: 'ProjetNormandie\ComptaBundle\Entity\Donation', manager_type: orm, group: "group.compta", label: "label.donation" }
        arguments: [ ~, ~, ~ ]
    sonata.admin.compta.compta:
        class: ProjetNormandie\ComptaBundle\Admin\ComptaAdmin
        tags:
            - { name: sonata.admin, model_class: 'ProjetNormandie\ComptaBundle\Entity\Compta', manager_type: orm, group: "group.compta", label: "label.compta" }
        arguments: [ ~, ~, ~ ]